import {
  pgTable,
  pgEnum,
  uuid,
  text,
  varchar,
  boolean,
  timestamp,
  integer,
  numeric,
  date,
  unique,
  index,
} from 'drizzle-orm/pg-core'

export const planEnum = pgEnum('plan', ['free', 'pro', 'enterprise'])
export const roleEnum = pgEnum('role', ['owner', 'admin', 'member'])

export const tenants = pgTable('tenants', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 255 }).notNull(),
  slug: varchar('slug', { length: 255 }).notNull().unique(),
  plan: planEnum('plan').notNull().default('free'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const users = pgTable(
  'users',
  {
    // Must match the UUID generated by Supabase Auth — do not auto-generate here
    id: uuid('id').primaryKey(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    name: varchar('name', { length: 255 }).notNull(),
    email: varchar('email', { length: 255 }).notNull().unique(),
    role: roleEnum('role').notNull().default('owner'),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => [index('users_tenant_idx').on(t.tenantId)],
)

export const projects = pgTable(
  'projects',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    name: text('name').notNull(),
    code: text('code').notNull().default(''),
    description: text('description'),
    color: text('color').notNull().default('#6366F1'),
    status: text('status').notNull().default('active'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => [
    index('projects_tenant_idx').on(t.tenantId),
    unique('projects_tenant_code_unique').on(t.tenantId, t.code),
  ],
)

export const features = pgTable(
  'features',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    projectId: uuid('project_id')
      .notNull()
      .references(() => projects.id),
    name: text('name').notNull(),
    description: text('description'),
    status: text('status').notNull().default('backlog'),
    priority: text('priority').notNull().default('medium'),
    displayOrder: integer('display_order').notNull().default(0),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => [
    index('features_tenant_idx').on(t.tenantId),
    index('features_project_idx').on(t.projectId),
    index('features_tenant_project_idx').on(t.tenantId, t.projectId),
  ],
)

export const teamMembers = pgTable(
  'team_members',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    projectId: uuid('project_id')
      .notNull()
      .references(() => projects.id),
    name: text('name').notNull(),
    email: text('email'),
    roleDescription: text('role_description'),
    dailyCapacityHours: numeric('daily_capacity_hours', { precision: 4, scale: 1 }).notNull().default('8'),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => [
    index('team_members_tenant_idx').on(t.tenantId),
    index('team_members_project_idx').on(t.projectId),
    index('team_members_tenant_project_idx').on(t.tenantId, t.projectId),
  ],
)

export const activities = pgTable(
  'activities',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    featureId: uuid('feature_id')
      .notNull()
      .references(() => features.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    startDate: timestamp('start_date'),
    dependsOnId: uuid('depends_on_id'),
    estimatedHours: numeric('estimated_hours', { precision: 5, scale: 1 }).notNull().default('0'),
    assignedMemberId: uuid('assigned_member_id').references(() => teamMembers.id, { onDelete: 'set null' }),
    estimatedEndDate: timestamp('estimated_end_date'),
    status: text('status').notNull().default('backlog'),
    displayOrder: integer('display_order').notNull().default(0),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => [
    index('activities_tenant_idx').on(t.tenantId),
    index('activities_feature_idx').on(t.featureId),
    index('activities_tenant_feature_idx').on(t.tenantId, t.featureId),
    index('activities_assigned_member_idx').on(t.assignedMemberId),
  ],
)

export type Tenant = typeof tenants.$inferSelect
export type NewTenant = typeof tenants.$inferInsert
export type User = typeof users.$inferSelect
export type NewUser = typeof users.$inferInsert
export type Project = typeof projects.$inferSelect
export type NewProject = typeof projects.$inferInsert
export type Feature = typeof features.$inferSelect
export type NewFeature = typeof features.$inferInsert
export type Activity = typeof activities.$inferSelect
export type NewActivity = typeof activities.$inferInsert
export type TeamMember = typeof teamMembers.$inferSelect
export type NewTeamMember = typeof teamMembers.$inferInsert

export const calendars = pgTable(
  'calendars',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    projectId: uuid('project_id')
      .notNull()
      .references(() => projects.id),
    year: integer('year').notNull(),
    workingDays: integer('working_days').array().notNull().default([1, 2, 3, 4, 5]),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => [
    unique('calendars_project_year_unique').on(t.projectId, t.year),
    index('calendars_tenant_idx').on(t.tenantId),
    index('calendars_project_idx').on(t.projectId),
  ],
)

export const calendarEventTypeEnum = pgEnum('calendar_event_type', [
  'holiday',
  'vacation',
  'day_off',
  'freeze',
  'extra_working',
])

export const calendarEvents = pgTable(
  'calendar_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    calendarId: uuid('calendar_id')
      .notNull()
      .references(() => calendars.id, { onDelete: 'cascade' }),
    type: calendarEventTypeEnum('type').notNull(),
    startDate: date('start_date').notNull(),
    endDate: date('end_date').notNull(),
    memberId: uuid('member_id').references(() => teamMembers.id, { onDelete: 'set null' }),
    label: text('label').notNull(),
  },
  (t) => [
    index('calendar_events_tenant_idx').on(t.tenantId),
    index('calendar_events_calendar_idx').on(t.calendarId),
    index('calendar_events_member_idx').on(t.memberId),
  ],
)

export type Calendar = typeof calendars.$inferSelect
export type NewCalendar = typeof calendars.$inferInsert
export type CalendarEvent = typeof calendarEvents.$inferSelect
export type NewCalendarEvent = typeof calendarEvents.$inferInsert

export const featureComments = pgTable(
  'feature_comments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id),
    featureId: uuid('feature_id')
      .notNull()
      .references(() => features.id, { onDelete: 'cascade' }),
    content: text('content').notNull(),
    type: text('type').notNull().default('update'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => [
    index('feature_comments_tenant_idx').on(t.tenantId),
    index('feature_comments_feature_idx').on(t.featureId),
    index('feature_comments_tenant_feature_idx').on(t.tenantId, t.featureId),
  ],
)

export type FeatureComment = typeof featureComments.$inferSelect
export type NewFeatureComment = typeof featureComments.$inferInsert
